### ISSUE TITLE
.insertMany() throw UniqueValidatorError because plugin throw TypeError

### ISSUE THREAD

**Issue by Mathiasduc** [blakehaswell/mongoose-unique-validator#68]
Hello,

when using ` AccessoryArray = await Accessory.insertMany(AccessoryArray);` on a model with uniqueValidator, the plugin will thow an Error because  `model` is not defined here: 
```
var model;
if (doc.constructor.name === 'Query') {
    model = doc.model;
} else if (isSubdocument) {
    model = doc.ownerDocument().model(doc.ownerDocument().constructor.modelName);
} else if (typeof doc.model === 'function') {
    model = doc.model(doc.constructor.modelName);
}
model.where({ $and: conditions }).count(function(err, count) {
   resolve(count === 0);
});
```
The error:
```
{ ValidationError: Software validation failed: name: Error, expected `name` to be unique. Value: `tawo`
at ValidationError.inspect (/path/to/project/node_modules/mongoose/lib/error/validation.js:63:24)
at formatValue (util.js:362:36)
at inspect (util.js:226:10)
at format (util.js:98:24)
at Console.warn (console.js:124:24)
at exports.createCertificationItems (/path/to/project/src/server/migrations/excelToDB.js:404:13)
at <anonymous>
at runMicrotasksCallback (internal/process/next_tick.js:121:5)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
errors: 
{ name: 
  { Error, expected `name` to be unique. Value: `tawo`
      at ValidatorError (/path/to/project/node_modules/mongoose/lib/error/validator.js:24:11)
      at validate (/path/to/project/node_modules/mongoose/lib/schematype.js:744:13)
      at /path/to/project/node_modules/mongoose/lib/schematype.js:787:15
      at <anonymous>
      at runMicrotasksCallback (internal/process/next_tick.js:121:5)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    message: 'Error, expected `name` to be unique. Value: `tawo`',
    name: 'ValidatorError',
    properties: [Object],
    kind: 'unique',
    path: 'name',
    value: 'tawo',
    reason: 
     TypeError: Cannot read property 'where' of undefined
         at /path/to/project/node_modules/mongoose-unique-validator/index.js:114:34
         at Promise (<anonymous>)
         at model.<anonymous> (/path/to/project/node_modules/mongoose-unique-validator/index.js:57:32)
         at /path/to/project/node_modules/mongoose/lib/schematype.js:776:26
         at Array.forEach (<anonymous>)
         at SchemaString.SchemaType.doValidate (/path/to/project/node_modules/mongoose/lib/schematype.js:750:19)
         at /path/to/project/node_modules/mongoose/lib/document.js:1464:9
         at _combinedTickCallback (internal/process/next_tick.js:131:7)
         at process._tickDomainCallback (internal/process/next_tick.js:218:9) } },
_message: 'Software validation failed',
name: 'ValidationError' }
```

**Comment by Mathiasduc** [comment]
I can try to make a PR for a quick fix, because i did not found a way to access the model in .insertMany validation functions.
